version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "requirements-dev.txt" }}-{{ checksum ".python-version" }}-{{ checksum "setup.py" }}
            - v2-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
            pip install -e .
      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements-dev.txt" }}-{{ checksum ".python-version" }}-{{ checksum "setup.py" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest tests --junitxml=test-results/results.xml
      - store_artifacts:
          path: test-results
      - store_test_results:
          path: test-results
